ServerRoot "/usr/local/apache2"
ServerName localhost

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule dir_module modules/mod_dir.so

ErrorLog /proc/self/fd/2
LogLevel warn

Listen 80

<VirtualHost *:80>

    ProxyPass "/api" "http://backend:5000/"
    ProxyPassReverse "/api" "http://backend:5000/"

</VirtualHost>